spring:
  application:
    name: shopping-cart
  config:
    import: "configserver:"
  cloud:
    config:
      fail-fast: true
      retry:
        # Повторные попытки получить конфиг из config-server, чтобы переживать гонку старта
        useRandomPolicy: true
        # Стартовая пауза между ретраями (мс)
        initial-interval: 2000
        # Множитель роста паузы между ретраями
        multiplier: 1.5
        # Максимальная пауза между ретраями (мс)
        max-interval: 6000
        # Максимальное количество попыток
        max-attempts: 20
      discovery:
        enabled: true
        service-id: config-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
