spring.application.name=aggregator

aggregator.kafka.bootstrap-servers=localhost:9092
aggregator.kafka.group-id=telemetry.aggregator.v1
aggregator.kafka.topics.sensors=telemetry.sensors.v1
aggregator.kafka.topics.snapshots=telemetry.snapshots.v1
aggregator.kafka.poll-timeout-ms=1000
