spring.application.name=analyzer

analyzer.kafka.bootstrap-servers=localhost:9092
analyzer.kafka.snapshots-group-id=analyzer-snapshots
analyzer.kafka.hub-events-group-id=analyzer-hub-events
analyzer.kafka.topics.snapshots=telemetry.snapshots.v1
analyzer.kafka.topics.hubs=telemetry.hubs.v1
analyzer.kafka.poll-timeout-ms=1000

analyzer.grpc.hub-router.address=static://localhost:59090

grpc.client.hub-router.address=static://localhost:59090
grpc.client.hub-router.enableKeepAlive=true
grpc.client.hub-router.keepAliveWithoutCalls=true
grpc.client.hub-router.negotiationType=plaintext

spring.datasource.url=jdbc:postgresql://localhost:5433/smarthome
spring.datasource.username=smarthome
spring.datasource.password=smarthome

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

logging.level.ru.yandex.practicum.analyzer=DEBUG
