analyzer:
  kafka:
    bootstrap-servers: "localhost:9092"
    snapshots-group-id: "analyzer-snapshots"
    hub-events-group-id: "analyzer-hub-events"
    topics:
      snapshots: "telemetry.snapshots.v1"
      hubs: "telemetry.hubs.v1"
    poll-timeout-ms: 1000

grpc:
  client:
    hub-router:
      address: static://localhost:59090
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/smarthome
    username: smarthome
    password: smarthome
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    ru.yandex.practicum.analyzer: DEBUG
